### ISSUE TITLE
Brotli compression

### ISSUE THREAD

**Issue by decadentsoup** [denysvitali/thebestmotherfuckingwebsite#36]
You can save a whoooole kilobyte with the Brotli compression algorithm. It's supported on [several browsers](https://caniuse.com/#feat=brotli).

```
$ curl -s https://thebestmotherfucking.website > index.html
$ gzip -k -9 index.html
$ brotli index.html
$ ls -lh index.html index.html.gz index.html.br
-rw-r--r-- 1 nnn nnn  14K Nov  5 00:36 index.html
-rw-r--r-- 1 nnn nnn 4.2K Nov  5 00:36 index.html.br
-rw-r--r-- 1 nnn nnn 5.2K Nov  5 00:36 index.html.gz
```

To do it with Nginx, first install the Brotli extension (on Arch Linux for example, via `pacman -S nginx-mod-brotli` then adding this to your `nginx.conf`:

```
# Outside of any of the blocks. The paths may vary for your system.
# This one is used for on-the-fly compression (see "brotli on").
load_module /usr/lib/nginx/modules/ngx_http_brotli_filter_module.so;
# This one is used if you precompress your files (see "brotli_static on").
load_module /usr/lib/nginx/modules/ngx_http_brotli_static_module.so;

# Within your server block when using on-the-fly compression.
brotli on;
brotli_comp_level 11; # if you want the best compression
```

**Comment by denysvitali** [comment]
Thank you! I'll fix my nginx config accordingly. At the moment we should have gzip as a compression method, but probably brotli is better. I just wonder if the two can coexist 🙄

**Comment by denysvitali** [comment]
Okay, I re-looked into this issue and noticed that it cannot currently be implemented with the nginx docker image that I'm using because it's based on Alpine 3.12 and [nginx-mod-http-brotli](https://pkgs.alpinelinux.org/package/edge/main/x86_64/nginx-mod-http-brotli) is only available on edge for now.

I'll keep the issue open, as soon as this lands on a stable release (and the official nginx Docker image uses that), I'll implement it :+1:

**Comment by denysvitali** [comment]
Closing - switched to GH Pages so this is not relevant anymore
