### ISSUE TITLE
Why is shit minified

### ISSUE THREAD

**Issue by acz13** [denysvitali/thebestmotherfuckingwebsite#4]
Seriously

It's not like the website is huge

**Comment by denysvitali** [comment]
Everything should be minified, especially if anyone can have the source.
Let me explain better: your browser doen't need all the junk like spaces and long function names to work properly, therefore if you're adding them you're wasting bandwith.

For a small website like this I agree with you: it doen't need to be minified, but if youstart using the best practices for small websites, then you'll do the same for every project and therefore we can make the internet fast again (citation needed).

If you want to see the source you're in the right place, just take a look at the `less/` folder and the `pug/` folder.

Maybe I should add `css/` to the .gitignore since it's only a compiled file

**Comment by acz13** [comment]
Problem is, site so bloated...

```
~/dev
❯ du -sh thebestmotherfuckingwebsite 
51M	thebestmotherfuckingwebsite
```

dafuq

**Comment by denysvitali** [comment]
Not sure if trolling
```
➜  git du -h thebestmotherfuckingwebsite --max-depth=0                              
316K    thebestmotherfuckingwebsite
```

**Comment by acz13** [comment]
oh, I was talking about the size of all the dependencies after `npm i`

**Comment by denysvitali** [comment]
That's the dependency hell of node, but it is needed in order to use less and the css minifier (along with the other tasks in the gulpfile)

**Comment by denysvitali** [comment]
I'm closing the issue, feel free to comment if you want to add something to the discussion or propose something 😄
