### ISSUE TITLE
inaccurate portrayal of IPoAC

### ISSUE THREAD

**Issue by oplik0** [denysvitali/thebestmotherfuckingwebsite#42]
As is even described on the Wikipedia page that the IPoAC links to, it's important to note that bandwidth is NOT a problem for this standard. In fact, it's trivial for an implementation of IPoAC to have bandwidth exceeding basically any home internet solution, with possibly hundreds of Gb/s. In fact, if we update the example from [said Wikipedia article](https://en.wikipedia.org/wiki/IP_over_Avian_Carriers) to use modern 1TB microSD cards (like SanDisk Extreme Pro 1TB) we will be close to 300Gb/s - and that's without even attempting to increase the number of SD cards, since microSDs are much smaller than standard SD cards and I'm fairly sure a homing pigeon would be able to carry more than 8.

Therefore as long as the loading of all resources is initiated at the same time, the IPoAC can easily provide the same delay for 50kB website and 500MB website.

I believe we should stop misleading people about the capabilities of IPoAC and acknowledge the superiority of this standard - and therefore, the suggestion that IPoAC users would have any problems with loading websites that load massive images or scripts should be removed or corrected to mention these facts.

Additionally, I'd suggest adding a paragraph about not using lazy loading, as that lazy method of "increasing website load times" actually hurts all IPoAC users in the world by massively increasing their delays and possibly causing them to wait hours longer for a simple website to load its images.

**Comment by denysvitali** [comment]
Thanks for opening this issue! I do really appreciate your concerns over this serious matter.

Indeed, a 500 MB website on IPoAC will take the same time as a 5k one. Unfortunately generally speaking a resource intensive website (e.g: one that is around 1-5 MB) will usually include an incredibile amount of resources from different hosts. One could argue that webpack and similar technologies are indeed a godsend for IPoAC since the resources usually get bundled in a single ".js" file and therefore the loading times for such a transport will be even faster than thebestmotherfucking.website (since it does include more than three resources).

I'll be more than happy to include a paragraph to better clarify your points.


🐦

**Comment by denysvitali** [comment]
Fixed in my most recent commit. Feel free to report any inaccuracy if you feel that it is still wrong by re-opening this issue :+1:
