### ISSUE TITLE
Remove joke about "reading disabilities"

### ISSUE THREAD

**Issue by YawarRaza7349** [denysvitali/thebestmotherfuckingwebsite#45]
In the "Legal" section, there's a joke about reading disabilities and reading slowly. There are actually people who read slowly due to things like dyslexia. Incidently, some of those people might find it straining to read the string of single word sentences later in the joke, adding insult to injury. There are other possible jokes that can be made about how short the license is.

**Comment by denysvitali** [comment]
I might agree, but you have to remember that it is still meant as a joke rather than as an offense.

If you really had something like dyslexia, or any other type of reading problem,  you might be offended by such a pun - but so can a person that doesn't have any reading problem when he is being called (again, with humor) a "motherfucker".

I'm more than happy to change it to not offend a category of people who might really have such problems: do you have any suggestion on a possible joke that doesn't offend anybody and that can replace that part?

Thanks for opening this issue 👍

**Comment by J0hsHH** [comment]
plezzz lets the "reading disabilities" be there

**Comment by denysvitali** [comment]
I've fixed this issue in an upcoming commit, thanks!
