### ISSUE TITLE
PIN number

### ISSUE THREAD

**Issue by arthurtiteica** [denysvitali/thebestmotherfuckingwebsite#9]
**P**ersonal **I**dentification **N**umber number is just wrong ;)

**Comment by denysvitali** [comment]
Thanks for opening this issue: [I know it's "wrong"](https://en.m.wikipedia.org/wiki/RAS_syndrome), but it is common to say "PIN Number", at least in my latitudes.
What do you think about it? Should I change it?

**Comment by arthurtiteica** [comment]
I'm not a native English speaker but on the internet circles I play it's not seen very well.

**Comment by denysvitali** [comment]
Neither am I, but I know that some acronyms are used recursively (like ATM Machine, PIN Number, NFC Communication, ...)
I'll keep this open, hopefully a third person may give an advice on this: it is a nice language "bug" btw 😄

**Comment by vktec** [comment]
I'd change it to either "PIN code" or just "PIN". Technically speaking, "code" is redundant too (personal identification number code), but it's commonly used (moreso than "PIN number" in my experience) and, to me, sounds better.

**Comment by denysvitali** [comment]
PIN code sounds good! 👍

**Comment by denysvitali** [comment]
0cb748c fixes the issue, if you have something to add, feel free to comment here or open a new issue.

Have a wonderful day! 🚀

**Comment by Kadigan** [comment]
I would say that "PIN number", despite being silly, _may have actual merit_.

And isn't that ironic that I'm the one saying this. _But - hear me out._

The acronym (and many others like it in frequent general use, like "ATM") functionally encroaches on the _proper noun_ territory, despite technically not being one. Due to this "overuse", it becomes progressively _opaque_. This leads to a situation where the acronym is not expanded at all (because it doesn't seem like something that needs to be understood), necessitating _a qualifier_ ("number"). And so, we get "ATM machines" and "PIN numbers".

Despite the horror it may induce in some, this is actually _language adaptation at work_. Which is _generally a good thing_.

I don't care if you change it or not - just thought I'd share my thoughts.
